### ISSUE TITLE
Kill job throws Access Denied

### ISSUE THREAD

**Issue by vogdb** [cargomedia/pulsar-rest-api#89]
```
2016-01-14 15:36:34.574 ERROR - Request { url: '/job/5697bd092b796b6251490da0/kill', params: {} } caught exception { [Error: Access denied] message: 'Access denied', code: 403 }
Error: Access denied
    at new AuthorizationError (/usr/lib/node_modules/pulsar-rest-api/lib/errors.js:25:15)
    at /usr/lib/node_modules/pulsar-rest-api/lib/authentication/authorization/index.js:26:19
    at Layer.handle [as handle_request] (/usr/lib/node_modules/pulsar-rest-api/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/lib/node_modules/pulsar-rest-api/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/usr/lib/node_modules/pulsar-rest-api/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/pulsar-rest-api/node_modules/express/lib/router/layer.js:82:5)
    at /usr/lib/node_modules/pulsar-rest-api/node_modules/express/lib/router/index.js:234:24
    at param (/usr/lib/node_modules/pulsar-rest-api/node_modules/express/lib/router/index.js:331:14)
    at param (/usr/lib/node_modules/pulsar-rest-api/node_modules/express/lib/router/index.js:347:14)
    at Function.proto.process_params (/usr/lib/node_modules/pulsar-rest-api/node_modules/express/lib/router/index.js:391:3)
```

**Comment by vogdb** [comment]
Fixed by a proper configuration of pulsar-rest-api.
